Fix links and remove overwriting CSS
radicalbarracuda/sf-feminist-book-club pull request #18
Opened 2017-04-10 19:17 UTC by pamo

This is a big PR but the typography lives in one place now.

2017-04-10 20:20 UTC, lizgene requested changes

2017-04-10 20:20 UTC, lizhubertz commented on _sass/_base.scss
>    margin: line-height(2) 0 0 line-height(-1);
While we're at it, can we get rid of this right margin on the header elements?

![image](https://cloud.githubusercontent.com/assets/4473327/24880722/4bfd2572-1df0-11e7-8f97-0658290ccbfd.png)

2017-04-10 20:20 UTC, lizhubertz commented on _posts/2017-03-19-audre-lorde-sister-outsider-study-guide.md
> +* Which essay stood out to you (positively or negatively) and why?
And let's kill this bullet point, since it's not actually part of any list.

2017-04-10 20:31 UTC, lizhubertz commented on _sass/_base.scss
>    margin: line-height(2) 0 0 line-height(-1);
And by `right` I mean `left`

2017-04-11 03:59 UTC, pamo commented
Done @lizhubertz

2017-04-11 05:04 UTC, lizhubertz commented
LGTM! 👍

2017-04-11 05:04 UTC, lizgene approved these changes

2017-04-11 05:04 UTC, merged