Jekyll plugins
radicalbarracuda/sf-feminist-book-club pull request #38
Opened 2017-04-15 20:44 UTC by pamo

## Why?

A variety of things we might find useful
* [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag)
* [jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap)
* [jemoji](https://github.com/jekyll/jemoji)

## What?
Basic configuration

## How can/should this be manually tested?

See details on each of the plugin's pages.

2017-04-15 21:51 UTC, lizgene requested changes
Where be your `Gemfile` & `Gemfile.lock`?

In case you ran `gem install gemname` - That will work locally, but you need to add the gem (preferably with a [version constraint](http://bundler.io/v1.5/gemfile.html)) to the `Gemfile` and then run a `bundle install`. That will update `Gemfile.lock` and you can commit them both.

2017-04-15 21:53 UTC, lizhubertz commented on _config.yml
> +  - jemoji
Clearly this is necessary for feminist book club study guides. 😂

2017-04-15 21:59 UTC, pamo commented
Oh ooops. Didn't think those were necessary for gh-pages

2017-04-16 03:42 UTC, pamo commented
@lizhubertz these are already present in `Gemfile.lock`

2017-04-16 20:24 UTC, lizhubertz commented
@pamo Right you are 👍 🚢

2017-04-16 20:24 UTC, lizgene approved these changes

2017-04-16 20:24 UTC, merged